"""
LightRAG singleton initializer.

Exposes:
  get_rag()          — returns the initialized LightRAG instance (lazy, once)
  insert_document()  — inserts a single document string into the graph/vector store

Storage layout (controlled by STORAGE_DIR in .env):
  <STORAGE_DIR>/   — working_dir handed to LightRAG; it creates all sub-dirs

LightRAG 1.4.x notes:
  - LightRAG is a @dataclass; all params are constructor kwargs (no nested objects
    except EmbeddingFunc which wraps the embedding callable).
  - initialize_storages() must be awaited before the first insert or query.
  - ainsert(input, ids=...) accepts a str or list[str]; ids is optional.
"""

from __future__ import annotations

import asyncio
import os

from dotenv import load_dotenv

load_dotenv(dotenv_path=".env", override=False)

from lightrag import LightRAG, QueryParam  # noqa: E402  (after load_dotenv)
from lightrag.utils import EmbeddingFunc  # noqa: E402
from lightrag.prompt import PROMPTS  # noqa: E402

from src.rag.llm_backend import llm_model_func  # noqa: E402
from src.rag.embedding import embedding_func, EMBEDDING_DIM  # noqa: E402
from src.rag.reranker import rerank_handler  # noqa: E402

# Ultra-lean extraction prompt for local LLMs
PROMPTS["entity_extraction"] = """-Goal-
Extract entities (nodes) and relationships (edges) from the text.

-Steps-
1. Identify all entities. For each: name, type, description.
2. Identify relationships between entities: source, target, relationship type, description.
3. Output strictly in the format:
entity<|>name<|>type<|>description
relation<|>source<|>target<|>type<|>description

-Entity Types-
["Person", "Organization", "Location", "Law", "Event", "Concept", "Date"]

-Real-time Document-
{input_text}
"""

PROMPTS["entity_extraction_examples"] = [
    """entity<|>Supreme Court Of India<|>Organization<|>Apex court of India.
entity<|>Constitution<|>Law<|>Supreme law of India.
relation<|>Supreme Court Of India<|>Constitution<|>interprets<|>The Court interprets the Constitution.
<|COMPLETE|>"""
]

_rag: LightRAG | None = None
_rag_lock: asyncio.Lock | None = None


def _get_lock() -> asyncio.Lock:
    """Return the singleton asyncio.Lock, creating it lazily inside a running loop."""
    global _rag_lock
    if _rag_lock is None:
        _rag_lock = asyncio.Lock()
    return _rag_lock


def _build_rag() -> LightRAG:
    """Construct a LightRAG instance with project-specific configuration."""
    storage_dir = os.getenv("STORAGE_DIR", "storage/")

    return LightRAG(
        working_dir=storage_dir,
        llm_model_func=llm_model_func,
        embedding_func=EmbeddingFunc(
            embedding_dim=EMBEDDING_DIM,
            max_token_size=8192,
            func=embedding_func,
        ),
        chunk_token_size=400,
        chunk_overlap_token_size=32,
        entity_extract_max_gleaning=0,
        llm_model_max_async=4,        # Stable concurrency for 8-16k context
        embedding_func_max_async=4,   # Matches LLM for stability
        max_parallel_insert=1,        # 1 doc at a time — no batch bottleneck
        rerank_model_func=rerank_handler, # Premium 2-stage retrieval
    )


async def get_rag() -> LightRAG:
    """Return the singleton LightRAG instance, initializing storages on first call.

    Uses an asyncio.Lock so concurrent coroutines cannot race to initialize
    the same instance simultaneously.
    """
    global _rag
    async with _get_lock():
        if _rag is None:
            _rag = _build_rag()
            await _rag.initialize_storages()
    return _rag


async def insert_document(text: str, doc_id: str | None = None) -> str:
    """Insert a single document into LightRAG.

    Args:
        text:   Raw document text to index.
        doc_id: Optional stable document ID. When None, LightRAG generates an
                MD5-based ID from the content.

    Returns:
        The tracking ID generated by LightRAG for this insert operation.
    """
    rag = await get_rag()
    ids = [doc_id] if doc_id is not None else None
    track_id = await rag.ainsert(text, ids=ids)
    return track_id
